import type { NextPage } from "next";
import Head from "next/head";
import styles from "@styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by betich's boilerplate Next.js template" />
      </Head>
      <main className={styles.container}>
        <h1 className={styles.header}>Next.js App</h1>
        <p className={styles.description}>
          Generated using{" "}
          <a href="https://github.com/betich/next-boilerplate" target="_blank" rel="noreferrer">
            {"betich's"}
          </a>{" "}
          Next.js boilerplate template
        </p>
      </main>
    </>
  );
};

export default Home;
